### ISSUE TITLE
Documentation: How do you pass in a custom template?

### ISSUE THREAD

**Issue by dubcanada** [tameraydin/ngToast#27]
I saw there is a PR where someone implements allowing you to pass in a custom toast template, but I can't seem to figure out how to do it properly.

https://github.com/tameraydin/ngToast/pull/2

Basically I'm using Zurb so I want to move the close button to the right of the HTML content, and change it to an a tag rather then a button.

**Comment by tameraydin** [comment]
Changes on that commit allow you to provide an template url by "template" attribute on <toast> element, but this is about container template, not the single toast message. So that doesn't work for you.

to move the close button to right, you can override bootstrap.css by adding these rules;
```css
.alert-dismissable, 
.alert-dismissible {
  padding-right: inherit;
  padding-left: 35px;
}
.alert-dismissable .close, 
.alert-dismissible .close {
  right: auto;
  left: -21px;
  float: left;
}
```
